<?php
    /**
     * Created by PhpStorm.
     * User: shameless
     * Date: 15/11/3
     * Time: 10:16
     */

return array(
    2 => array(
        //键名,含义,默认值,备注
        array('RTC_LV1_BASEPOINT' , '初级底' ,2,''),
        array('RTC_LV1_ENTER' , '初级进入门槛' ,1000,''),
        array('RTC_LV1_KICKOUT' , '初级踢人门槛' ,708,''),
        array('RTC_LV1_BASERATE' , '初级场基础倍率' ,2,''),
        array('RTC_LV1_ADDRATE1' , '初级场增加倍率1' ,1,''),
        array('RTC_LV1_ADDRATE2' , '初级场增加倍率2' ,2,''),
        array('RTC_LV1_ADDRATE3' , '初级场增加倍率3' ,4,''),
        array('RTC_LV1_ADDRATE4' , '初级场增加倍率4' ,8,''),
        array('RTC_LV1_ADDRATE5' , '初级场加满倍率' ,16,''),
        array('RTC_LV1_MAXROUND' , '初级场最大圈数' ,10,''),
        array('RTC_LV2_BASEPOINT' , '中级底' ,20,''),
        array('RTC_LV2_ENTER' , '中级进入门槛' ,10000,''),
        array('RTC_LV2_KICKOUT' , '中级踢人门槛' ,7080,''),
        array('RTC_LV2_BASERATE' , '中级场基础倍率' ,2,''),
        array('RTC_LV2_ADDRATE1' , '中级场增加倍率1' ,1,''),
        array('RTC_LV2_ADDRATE2' , '中级场增加倍率2' ,2,''),
        array('RTC_LV2_ADDRATE3' , '中级场增加倍率3' ,4,''),
        array('RTC_LV2_ADDRATE4' , '中级场增加倍率4' ,8,''),
        array('RTC_LV2_ADDRATE5' , '中级场加满倍率' ,16,''),
        array('RTC_LV2_MAXROUND' , '中级场最大圈数' ,10,''),
        array('RTC_LV3_BASEPOINT' , '高级底' ,100,''),
        array('RTC_LV3_ENTER' , '高级进入门槛' ,50000,''),
        array('RTC_LV3_KICKOUT' , '高级踢人门槛' ,35400,''),
        array('RTC_LV3_BASERATE' , '高级场基础倍率' ,2,''),
        array('RTC_LV3_ADDRATE1' , '高级场增加倍率1' ,1,''),
        array('RTC_LV3_ADDRATE2' , '高级场增加倍率2' ,2,''),
        array('RTC_LV3_ADDRATE3' , '高级场增加倍率3' ,4,''),
        array('RTC_LV3_ADDRATE4' , '高级场增加倍率4' ,8,''),
        array('RTC_LV3_ADDRATE5' , '高级场加满倍率' ,16,''),
        array('RTC_LV3_MAXROUND','高级场最大圈数',10,''),
        array('RTC_TAX_RATE' , '扎金花的税率1～100' ,3,''),
        array('RTC_TABLE_START_SECOND' , '等待开局的秒 2～100' ,5,''),
        array('RTC_FIRST_USER_ACTION_TIMEOUT' , '开局用户操作超时 5～32' ,12,''),
        array('RTC_USER_ACTION_TIMEOUT' , '用户操作超时 3～30' ,10,''),
    ),


    4 => array(
        array('RTC_LV1_BASEPOINT_NN','lv1底',1,''),
        array('RTC_LV2_BASEPOINT_NN','lv2底',10,''),
        array('RTC_LV3_BASEPOINT_NN','lv3底',100,''),
        array('RTC_LV4_BASEPOINT_NN','lv4底',500,''),
        array('RTC_LV5_BASEPOINT_NN','lv5底',1000,''),
        array('RTC_LV6_BASEPOINT_NN','lv6底',5000,''),
        array('RTC_LV1_BASEPOINT_NN100','百人牛牛lv1底',100,''),
        array('RTC_LV2_BASEPOINT_NN100','百人牛牛lv2底',10000,''),
        array('RTC_LV1_ENTER_NN','lv1进入门槛',100,''),
        array('RTC_LV1_KICKOUT_NN','lv1踢人门槛',75,''),
        array('RTC_LV2_ENTER_NN','lv2进入门槛',1000,''),
        array('RTC_LV2_KICKOUT_NN','lv2踢人门槛',750,''),
        array('RTC_LV3_ENTER_NN','lv3进入门槛',10000,''),
        array('RTC_LV3_KICKOUT_NN','lv3踢人门槛',7500,''),
        array('RTC_LV4_ENTER_NN','lv4进入门槛',50000,''),
        array('RTC_LV4_KICKOUT_NN','lv4踢人门槛',37500,''),
        array('RTC_LV5_ENTER_NN','lv5进入门槛',100000,''),
        array('RTC_LV5_KICKOUT_NN','lv5踢人门槛',75000,''),
        array('RTC_LV6_ENTER_NN','lv6进入门槛',500000,''),
        array('RTC_LV6_KICKOUT_NN','lv6踢人门槛',375000,''),
        array('RTC_LV1_ENTER_NN100','百人牛牛lv1进入门槛',100000,''),
        array('RTC_LV1_KICKOUT_NN100','百人牛牛lv1踢人门槛',75000,''),
        array('RTC_LV2_ENTER_NN100','百人牛牛lv2进入门槛',500000,''),
        array('RTC_LV2_KICKOUT_NN100','百人牛牛lv2踢人门槛',375000,''),
        array('RTC_NEW_TABLE_ROBOT_RATE','新开桌分配机器人几率',70,''),
        array('RTC_TAX_RATE_NN','税率 1～100',3,''),
        array('RTC_TABLE_START_SECOND_NN','等待开局的秒 2～100',5,''),
        array('RTC_FIRST_USER_ACTION_TIMEOUT_NN','开局用户操作超时 5～32 ',12,''),
        array('RTC_USER_ACTION_TIMEOUT_NN','开局用户操作超时 3～30 ',10,''),
    ),


    3 => array(
        array('RTC_LV1_BASEPOINT_NN','lv1底',1,''),
        array('RTC_LV2_BASEPOINT_NN','lv2底',10,''),
        array('RTC_LV3_BASEPOINT_NN','lv3底',100,''),
        array('RTC_LV4_BASEPOINT_NN','lv4底',500,''),
        array('RTC_LV5_BASEPOINT_NN','lv5底',1000,''),
        array('RTC_LV6_BASEPOINT_NN','lv6底',5000,''),
        array('RTC_LV1_BASEPOINT_NN100','百人牛牛lv1底',100,''),
        array('RTC_LV2_BASEPOINT_NN100','百人牛牛lv2底',10000,''),
        array('RTC_LV1_ENTER_NN','lv1进入门槛',100,''),
        array('RTC_LV1_KICKOUT_NN','lv1踢人门槛',75,''),
        array('RTC_LV2_ENTER_NN','lv2进入门槛',1000,''),
        array('RTC_LV2_KICKOUT_NN','lv2踢人门槛',750,''),
        array('RTC_LV3_ENTER_NN','lv3进入门槛',10000,''),
        array('RTC_LV3_KICKOUT_NN','lv3踢人门槛',7500,''),
        array('RTC_LV4_ENTER_NN','lv4进入门槛',50000,''),
        array('RTC_LV4_KICKOUT_NN','lv4踢人门槛',37500,''),
        array('RTC_LV5_ENTER_NN','lv5进入门槛',100000,''),
        array('RTC_LV5_KICKOUT_NN','lv5踢人门槛',75000,''),
        array('RTC_LV6_ENTER_NN','lv6进入门槛',500000,''),
        array('RTC_LV6_KICKOUT_NN','lv6踢人门槛',375000,''),
        array('RTC_LV1_ENTER_NN100','百人牛牛lv1进入门槛',100000,''),
        array('RTC_LV1_KICKOUT_NN100','百人牛牛lv1踢人门槛',75000,''),
        array('RTC_LV2_ENTER_NN100','百人牛牛lv2进入门槛',500000,''),
        array('RTC_LV2_KICKOUT_NN100','百人牛牛lv2踢人门槛',375000,''),
        array('RTC_NEW_TABLE_ROBOT_RATE','新开桌分配机器人几率',70,''),
        array('RTC_TAX_RATE_NN','税率 1～100',3,''),
        array('RTC_TABLE_START_SECOND_NN','等待开局的秒 2～100',5,''),
        array('RTC_FIRST_USER_ACTION_TIMEOUT_NN','开局用户操作超时 5～32 ',12,''),
        array('RTC_USER_ACTION_TIMEOUT_NN','开局用户操作超时 3～30 ',10,''),
    )
);